import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@/app/fonts/material-symbols.css"; // Import Material Symbols CSS
import Provider from "./_trpc/provider";
import { NextAuthProvider } from "@/components/providers/session-provider";

// Local Font Configuration
// NOTE: Ensure the font files are placed in 'src/app/fonts/' as per OFFLINE_GUIDE.md
// UNCOMMENT THE BLOCKS BELOW AFTER DOWNLOADING THE FONT FILES

/*
const geistSans = localFont({
  src: "./fonts/GeistVF.woff2",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap", // Ensure fallback text is shown immediately
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff2",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap",
});

const vazirmatn = localFont({
  src: "./fonts/Vazirmatn-Variable.woff2", // Assuming variable font
  variable: "--font-vazir", // Changed to match globals.css var(--font-vazir)
  weight: "100 900",
  display: "swap",
});
*/

export const metadata: Metadata = {
  title: "Gemini Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      {/*
        NOTE: The <head> link to Google Fonts has been removed for offline support.
        Material Symbols are now loaded via 'material-symbols.css' and local font files.
      */}
      {/*
        NOTE: When local fonts are enabled, update the className below to include:
        ${geistSans.variable} ${geistMono.variable} ${vazirmatn.variable}
      */}
      <body
        className={`antialiased`}
      >
        <NextAuthProvider>
          <Provider>{children}</Provider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
